services:
  servidor:
    build:
      context: .              
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"

  cliente1:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - servidor
    stdin_open: true
    tty: true

  cliente2:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - servidor
    stdin_open: true
    tty: true

  cliente3:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - servidor
    stdin_open: true
    tty: true