services:
  servidor:
    build:
      context: .              
      dockerfile: Dockerfile.server
      
    ports:
      - "8080:8080"


  cliente1:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - servidor
    stdin_open: true
    tty: true

  cliente2:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - servidor
    stdin_open: true
    tty: true

  cliente3:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - servidor
    stdin_open: true
    tty: true